:!sectids:

== Why is this an issue?

Browsers optimize rendering performance by batching and combining similar operations.
However, when making multiple CSS changes at once, it can disrupt the browser's optimization mechanisms.
Applying changes individually allows the browser to better optimize the rendering process.

Making multiple CSS changes in a single batch can trigger multiple reflows and repaints in the browser.
Reflows and repaints are resource-intensive operations that can lead to performance issues.
Applying changes individually minimizes the number of reflows and repaints, improving overall page performance.

== How to fix it
=== Noncompliant code example

Here's an example in JavaScript and CSS to illustrate this rule:

[source,html,data-diff-id="3",data-diff-type="noncompliant"]
----
<script>
  element.style.height = "800px";
  element.style.width = "600px"; // Noncompliant
  element.style.color = "red"; // Noncompliant
</script>
----

=== Compliant solution

[source,html,data-diff-id="10",data-diff-type="compliant"]
----
<style>
  .in-error {
    color: red;
    height: 800px;
    width: 800px;
  }
</style>

<script>
  element.addClass("in-error"); // Compliant
</script>
----

In the first example, multiple CSS properties are set in a single batch, while in the second example, changes are applied through a CSS class.

== Resources

=== Documentation

- https://github.com/cnumr/best-practices/blob/main/chapters/BP_045_en.md[CNumR best practices] - Modify several CSS properties at once
