#!/usr/bin/env sh

# Define CodeNarc version
codenarcVersion="2.2.2"

# Build CodeNarc
cd codenarc-converter/CodeNarc
./gradlew

# Deploy to local repository
mvn install:install-file -Dfile=build/libs/CodeNarc-${codenarcVersion}.jar -DgroupId=org.codenarc -DartifactId=CodeNarc -Dversion=${codenarcVersion} -Dpackaging=jar

