name: Export rules

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '.github/**/*.yml'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  export:
    name: Export
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'

      - name: Build
        run: mvn -e -B install

      - name: Retrieve current version
        id: version
        run: |
          echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Export
        run: |
          mkdir -p dist && \
          java -jar ./tools/rule-exporter/target/rule-exporter-${{ steps.version.outputs.version }}.jar \
          ./ecocode-rules-specifications/target/ecocode-rules-specifications-${{ steps.version.outputs.version }}.jar \
          ./dist/rules.json

      - name: Archive artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: export
    permissions:
      pages: write    # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: rules
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
